#!/bin/bash

set -euo pipefail

[ -v SSL_DIR ] || SSL_DIR=""
[ -n "${SSL_DIR}" ] || SSL_DIR="/.ssl"
acme-init

# Only run this in the event that it's needed
[ -n "${INIT_DB_STORE:-}" ] && init-db "${@}"

# Only run this in the event that it's needed
[ -n "${BOOT_DB_STORE:-}" ] && boot-db "${@}"
